### ISSUE TITLE
Let "Hold to PvP" translatable

### ISSUE THREAD

**Issue by marcopaggioro** [Quared0/HubPvP#6]
Insert in config.yml the item lore "Hold to PvP"

**Comment by Quared0** [comment]
You can do this, it should be found under the configuration variable "items.weapon.name". Default value: &7> &#db86e6&lP&#da85d0&lv&#d984ba&lP &#d883a4&lS&#d8818d&lw&#d78077&lo&#d67f61&lr&#d57e4b&ld &7<

You can change this to whatever, it looks like jibberish since it is a bunch of colour codes to create the gradient effect.
